services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: meu-amigo-pet
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data